
server:
  port: 5003
spring:
  application:
    name: SUBMISSION-SERVICE
 
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/submission_service
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update 
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8075/eureka
    
  
